# Generated by Django 5.1.7 on 2025-04-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='rfid_tag',
        ),
    ]
